version 0.0.1a

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 # DelphineOS installation script
 #
@@ -7,15 +7,17 @@
 #	 - Create directories, ...
 
 
-FPC_VERSION="1.0.10"   # Current FPC version
-VERSION="0.0.0e"      # Current DelphineOS version
+FPC_VERSION="1.0.10"    # Current FPC version
+NASM_VERSION="0.98.38"  # Current NASM version
+VERSION="0.0.1"         # Current DelphineOS version
 NOT_FOUND="\033[31;1mnot found\033[0m"
 
+OS=`uname -a|cut -d" " -f1`
 
-compile_kernel()
+
+check_deps()
 {
-
-   echo -n "Check if the FPC is present...   "
+   echo -en "Check if the FPC is present...\t\t\t"
 
    PPC=$(ppc386 -iV 2> /dev/null)
 
@@ -27,14 +29,14 @@ compile_kernel()
         exit;
    fi
 
-   echo "            OK (version $PPC)"
+   echo "OK (version $PPC)"
 
    if [ $PPC != $FPC_VERSION ]; then
         echo -e "\033[31;1mWARNING: Latest version of the FPC is version $FPC_VERSION\033[0m"
    fi
 
 
-   echo -n "Check FPC configuration...   "
+   echo -en "Check FPC configuration...\t\t\t"
    echo "begin" > test.pp
    echo "end." >> test.pp
    PPC=$(ppc386 test.pp 2> /dev/null)
@@ -49,23 +51,23 @@ compile_kernel()
 
    rm -f test*
 
-   echo "                OK"
+   echo "OK"
 
-   echo -n "Check if nasm is present...   "
+   echo -en "Check if nasm is present...\t\t\t"
 
    nasm -v 2>&1 > /dev/null
 
    if [ ! $? -eq 0 ]; then
         echo -e $NOT_FOUND
         echo;
-        echo -e "\033[31;1mWarning: Please install NASM 0.98 or newer\033[0m"
+        echo -e "\033[31;1mWarning: Please install NASM $NASM_VERSION or newer\033[0m"
         echo;echo;
         exit;
    fi
 
-   echo "               OK"
+   echo "OK"
 
-   echo -n "Check if gcc is present...   "
+   echo -en "Check if gcc is present...\t\t\t"
 
    gcc -v 2> /dev/null
 
@@ -77,11 +79,21 @@ compile_kernel()
         exit;
    fi
 
-   echo "                OK"
+   echo "OK"
 
-   echo -n "Compiling DelphineOS kernel...   "
+}
+compile_kernel()
+{
 
-   make > kernel.log 2> kernel.log
+   echo -en "Compiling DelphineOS kernel...\t\t\t"
+
+	if [ "$OS" == "Linux" ]; then
+   	make > kernel.log 2> kernel.log
+	fi
+
+	if [ "$OS" == "FreeBSD" ]; then
+   	gmake > kernel.log 2> kernel.log
+	fi
 
    if [ ! $? -eq 0 ]; then
 	echo -e "\033[31;1mCompilation error.\n\nPlease see kernel.log\033[0m"
@@ -94,14 +106,30 @@ compile_kernel()
    fi
    
    if [ -f $1 ]; then
-      losetup -o 32256 /dev/loop1 $1
-      mount -t ext2 /dev/loop1 wxy/ -o loop 2> /dev/null > /dev/null
+		if [ "$OS" == "Linux" ]; then
+      	losetup -o 32256 /dev/loop1 $1
+			mount -t ext2 /dev/loop1 wxy/ -o loop 2> /dev/null > /dev/null
+		fi
+
+		if [ "$OS" == "FreeBSD" ]; then
+			MD_DEVICE=`mdconfig -a -t vnode -f $1`
+			mount_ext2fs /dev/"$MD_DEVICE"s1 wxy/
+		fi
+
+
       if [ ! $? -eq 0 ]; then
-           echo;
-           echo -e "\033[31;1m\nCannot mount $1. Check if loopback is activated in your kernel.\033[0m"
-	   echo;
-	   rm -rf wxy/
-           exit;
+			echo;
+			if [ "$OS" == "Linux" ]; then
+				echo -e "\033[31;1m\nCannot mount $1. Check if loopback is activated in your kernel\033[0m"
+				losetup -d /dev/loop1
+			fi
+			if [ "$OS" == "FreeBSD" ]; then
+				echo -e "\033[31;1m\nCannot mount $1. Check if EXT2FS is in your kernel\033[0m"
+				mdconfig -d -u $MD_DEVICE
+			fi
+	   	echo;
+	   	rm -rf wxy/
+      	exit;
       fi
    else
       mount -t ext2 $1 wxy/ 2> /dev/null > /dev/null
@@ -114,55 +142,66 @@ compile_kernel()
       fi
    fi
 
-   echo "            OK"
+   echo "OK"
 
-   echo -n "Copying kernel to $1...   "
+   echo -en "Copying kernel to $1...\t"
 
    cp ./src/kernel/kernel wxy/
 
    if [ -f $1 ]; then
-        ./mkboot /dev/loop1 wxy/kernel
+		if [ "$OS" == "Linux" ]; then
+			./mkboot /dev/loop1 wxy/kernel
+		fi
+		if [ "$OS" == "FreeBSD" ]; then
+			dd if=/dev/"$MD_DEVICE"s1 of=ext2.sb bs=512 count=10 2> /dev/null
+			./mkboot ext2.sb wxy/kernel
+			rm ext2.sb
+		fi
    else
         ./mkboot $1 wxy/kernel
    fi
 
-   echo -e "\t\t\b\b\bOK"
+   echo "OK"
 
-   echo -n 'Compiling boot sector file...   '
+   echo -en 'Compiling boot sector file...\t\t\t'
    nasm ./src/boot/boot.S
-   echo "             OK"
+   echo "OK"
 
    #Copying files to mount point
    
    #FIXME: test if files already exist before copying them
 
-   mkdir wxy/bin 2> /dev/null
-   mkdir wxy/etc 2> /dev/null
-   mkdir wxy/dev 2> /dev/null
-   mkdir wxy/tmp 2> /dev/null
-   mkdir wxy/sbin 2> /dev/null
-   mknod wxy/dev/null c 1 0 2> /dev/null
-   mknod wxy/dev/zero c 6 0 2> /dev/null
-   mknod wxy/dev/keyb c 2 0 2> /dev/null
-   mknod wxy/dev/tty  c 5 0 2> /dev/null
-   mknod wxy/dev/tty0 c 4 0 2> /dev/null
-   mknod wxy/dev/tty1 c 4 1 2> /dev/null
-   mknod wxy/dev/tty2 c 4 2 2> /dev/null
-   mknod wxy/dev/tty3 c 4 3 2> /dev/null
+	if [ ! -e base/dev/null ]; then
+#		mknod wxy/dev/tty  c 5 0 2> /dev/null
+		mknod base/dev/tty1 c 4 1 2> /dev/null
+		mknod base/dev/tty2 c 4 2 2> /dev/null
+		mknod base/dev/tty3 c 4 3 2> /dev/null
+		mknod base/dev/tty4 c 4 4 2> /dev/null
+		mknod base/dev/tty5 c 4 5 2> /dev/null
+		mknod base/dev/tty6 c 4 6 2> /dev/null
+		mknod base/dev/tty7 c 4 7 2> /dev/null
+		mknod base/dev/tty8 c 4 8 2> /dev/null
+		mknod base/dev/null c 1 0 2> /dev/null
+		mknod base/dev/zero c 6 0 2> /dev/null
+		chmod 666 base/dev/*
+	fi
 
-   cp base/sbin/*  wxy/sbin/
-   cp base/bin/*   wxy/bin/
-   cp base/etc/*   wxy/etc/
+   cp -R base/*  wxy/
+   chmod 777 wxy/tmp
+	umount wxy/
 
    if [ -f $1 ]; then
-	umount wxy/
-	dd if=src/boot/boot of=/dev/loop1 2> /dev/null
-	losetup -d /dev/loop1
-	chmod a+rw $1
+		if [ "$OS" == "Linux" ]; then
+			dd if=src/boot/boot of=/dev/loop1 2> /dev/null
+			losetup -d /dev/loop1
+		fi
+		if [ "$OS" == "FreeBSD" ]; then
+			dd if=src/boot/boot of=/dev/"$MD_DEVICE"s1 2> /dev/null
+			mdconfig -d -u $MD_DEVICE
+		fi
+		chmod a+rw $1
    else
-   	./mkboot $1 wxy/kernel
-	dd if=./src/boot/boot of=$1 2> /dev/null
-	umount wxy/
+		dd if=./src/boot/boot of=$1 2> /dev/null
    fi
 
    rm -rf wxy
@@ -178,14 +217,18 @@ echo; echo;
 echo -e "\033[32;1mDelphineOS $VERSION Installation:\033[0m"
 
 if [ $(whoami) != "root" ]; then
-     echo;echo;
-     echo "Only root can execute this script"
-     echo;echo;
-     exit;  
+	echo;echo;
+	echo "Only root can execute this script"
+	echo;echo;
+	exit;  
 fi
+
+echo; check_deps
 
 mkdir wxy 2> /dev/null
 
+echo;
+echo -e "Edit \033[32;1msrc/include/kernel/config.inc\033[0m for kernel configuration";
 echo;
 echo "Where do you want to install DelphineOS:"
 echo;
@@ -201,80 +244,101 @@ if [ "$REP" == "" ]; then
 fi
 
 case $REP in
-     1) echo;
-        echo -e "\033[32;1mCreating Bochs environment:\033[0m"
-        echo;
-        echo -n "Check if Bochs is present...   "
-	bochs --help 2> /dev/null
-	if [ ! $? -eq 0 ]; then
-	     echo -e $NOT_FOUND
-	     echo;
-	     echo -e "\033[31;1mWarning: Please install Bochs 2.0 or newer\033[0m"
-	     echo;echo;
-	     exit;
-	fi
 
-	echo "              OK"
+	1) echo;
+		echo -e "\033[32;1mCreating Bochs environment:\033[0m"
+		echo;
+		echo -en "Check if Bochs is present...\t\t\t"
+		bochs --help 2> /dev/null
+		if [ ! $? -eq 0 ]; then
+			echo -e $NOT_FOUND
+			echo;
+			echo -e "\033[31;1mWarning: Please install Bochs 2.0.2 or newer\033[0m"
+			echo;echo;
+			exit;
+		fi
 
-	if [ ! -e ./bochs/delphineOS.img ]; then
-	     echo -n "Creating HDD image (10Mb) using bximage...   "
-	     echo -e "\n\n\n" > options
-	     bximage < options > /dev/null
-	     rm -f options
+		echo "OK"
 
-	     mv c.img delphineOS.img
+		if [ ! -e ./bochs/delphineOS.img ]; then
+			echo -en "Creating HDD image (20Mb)...\t\t\t"
 
-	     rm -f c.img
-	     echo "OK"
-	     echo -n "Formatting HDD image (ext2)...   "
-	     losetup -o 32256 /dev/loop6 delphineOS.img
-	     mke2fs /dev/loop6 -F -q 2> /dev/null
-	     losetup -d /dev/loop6
-	     echo "            OK"
-	else
-	     mv ./bochs/delphineOS.img delphineOS.img
-	fi
+			echo -e "\n\n20\n\n" > options
+			bximage < options > /dev/null
+			rm -f options
+			mv c.img bochs/delphineOS.img
 
-	compile_kernel delphineOS.img
+			echo "OK"
 
-	losetup /dev/loop1 delphineOS.img
-	cp ./src/boot/mbr partoche
-	echo -n -e "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80\x01" >> partoche
-	echo -n -e "\x01\x00\x83\x0F\x3F\x13\x3F\x00\x00\x00\x81\x4e\x00\x00\x00\x00" >> partoche
-	echo -n -e "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" >> partoche
-	echo -n -e "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" >> partoche
-	echo -n -e "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x55\xAA" >> partoche
-	dd if=partoche of=/dev/loop1 2> /dev/null
-	rm partoche
-	losetup -d /dev/loop1
+			echo -en "Formatting HDD image (ext2)...\t\t\t"
 
-	mv delphineOS.img bochs/delphineOS.img
-	echo;
-	echo -e "\033[32;1mTake a look at bochs/bochsrc (lines 89 and 132) and run Bochs  :-)\033[0m"
-	;;
+			# First, put mbr and partition table on disk image
+			nasm ./src/boot/mbr.S
 
-     2) echo;
-        echo -e "\033[32;1mCreating a bootable floppy:\033[0m"
-	echo;
-        compile_kernel /dev/fd0
-	echo;
-	echo "You can now reboot with /dev/fd0. It should be OK  :-)";;
+			cp ./src/boot/mbr partoche
+			echo -en "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x80\x01" >> partoche
+			echo -en "\x01\x00\x83\x0F\x3F\x27\x3F\x00\x00\x00\x41\x9D\x00\x00\x00\x00" >> partoche
+			echo -en "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" >> partoche
+			echo -en "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" >> partoche
+			echo -en "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x55\xAA" >> partoche
+			dd if=partoche of=bochs/delphineOS.img conv=notrunc 2> /dev/null
+			rm partoche
 
-     3) echo;
-        echo -n "Partition (ex: /dev/hda3): "
-	read PART
-	echo; echo -en "\033[31;1mWARNING: \033[0m"
-	echo -n "Are you sure you want to install DelphineOS on $PART [y/n]: "
-	read REP2
-	echo;
-	if [ "$REP2" != "y" ]; then
-	   echo "Bye"; echo;
-	   exit;
-	fi
-        compile_kernel $PART
-	;;
+			if [ "$OS" == "Linux" ]; then
+				losetup -o 32256 /dev/loop1 bochs/delphineOS.img
+				mke2fs -F -q /dev/loop1 2> /dev/null
+				losetup -d /dev/loop1
+			fi
 
-     *) echo -e "\n\033[31;1mIs your brain dead ???   :-)\033[0m";
+			if [ "$OS" == "FreeBSD" ]; then
+				MD_DEVICE=`mdconfig -a -t vnode -f bochs/delphineOS.img`
+				mke2fs -F -q /dev/"$MD_DEVICE"s1 2> /dev/null
+				mdconfig -d -u $MD_DEVICE
+			fi
+
+			echo "OK"
+		fi
+
+		compile_kernel bochs/delphineOS.img
+
+		chmod 666 bochs/delphineOS.img
+
+		echo;
+		echo -e "\033[32;1mUse this for bochs:\033[0m"
+		echo -e "ata0-master: type=disk, mode=flat, path="bochs/delphineOS.img", cylinders=40,\nheads=16, spt=63, model="Bochs HD""
+		;;
+
+
+	2) echo;
+		echo -e "\033[32;1mCreating a bootable floppy:\033[0m"
+		echo;
+		compile_kernel /dev/fd0
+		echo;
+		echo "You can now reboot with /dev/fd0. It should be OK  :-)"
+		;;
+
+
+	3) echo;
+		echo -n "Partition (ex: /dev/hda3): "
+		read PART
+		echo; echo -en "\033[31;1mWARNING: \033[0m"
+		echo -n "Are you sure you want to install DelphineOS on $PART [y/n]: "
+		read REP2
+		echo;
+
+		if [ "$REP2" != "y" ]; then
+	   	echo "Bye"; echo;
+	   	exit;
+		fi
+
+		compile_kernel $PART
+		echo;
+		echo "Reboot and try DelphineOS   :-)"
+		;;
+
+
+	*) echo -e "\n\033[31;1mIs your brain dead ???   :-)\033[0m";
+
 esac
 
 
@@ -287,23 +351,17 @@ esac
         echo
         echo -n "Creating 'flagger' script...   "
 
-	echo "#!/bin/sh" > flagger
+	echo "#!/bin/bash" > flagger
 	echo "#delphineOS" >> flagger
 	echo "" >> flagger
 	echo "TEST=\`echo \$@ |grep -e '-c '\`" >> flagger
 	echo "" >> flagger
 	echo "if [ ! -n \"\$TEST\" ]; then" >> flagger
-	echo -n "gcc \$@ -nostdinc -nostartfiles -I$PWD/src/include -fno-builtin -static " >> flagger
-	echo -n "$PWD/lib/dietlibc.a -Xlinker $PWD/lib/start.o -Xlinker $PWD/lib/environ.o " >> flagger
+	echo -n "gcc \$@ -nostdinc -nostartfiles -nostdlib -I$PWD/src/include -static " >> flagger
+	echo -n "-Xlinker $PWD/lib/start.o -Xlinker $PWD/lib/environ.o -Xlinker $PWD/lib/dietlibc.a " >> flagger
 	echo "-Xlinker -T -Xlinker $PWD/lib/c_linkfile -Xlinker --strip-all" >> flagger
 	echo "else" >> flagger
-	echo "gcc \$@ -nostdinc -I$PWD/src/include -fno-builtin" >> flagger
-
-#	echo -n "gcc \$@ -nostdinc -nostdlib -nodefaultlibs -nostartfiles -I$PWD/src/include -I. -Wall -fno-builtin -static " >> flagger
-#	echo -n "$PWD/lib/dietlibc.a -Xlinker $PWD/lib/start.o -Xlinker $PWD/lib/environ.o " >> flagger
-#	echo "-Xlinker -T -Xlinker $PWD/lib/c_linkfile" >> flagger
-#	echo "else" >> flagger
-#	echo "gcc \$@ -nostdinc -nostdlib -nodefaultlibs -nostartfiles -I$PWD/src/include -I. -Wall -fno-builtin -static" >> flagger
+	echo "gcc \$@ -nostdinc -I$PWD/src/include" >> flagger
 
 	echo "fi" >> flagger
 	chmod +x flagger
